# Server configurations
server:
  host: "0.0.0.0"
  port: 8080

# Database credentials
database:
  dialect: "mysql"
  host: "url-shortener.ch8t8lotsnfu.eu-west-1.rds.amazonaws.com"
  port: 3306
  db_name: "url_shortener"
  charset: "utf8"
  region: "eu-west-1"