---
apiVersion: apps/v1
kind: Deployment                  # Type of Kubernetes resource
metadata:
  name: url-shortener-api         # Name of the Kubernetes resource
spec:
  replicas: 3                     # Number of pods to run at any given time
  selector:
    matchLabels:
      app: url-shortener          # This deployment applies to any Pods matching the specified label
  template:                       # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                     # The labels that will be applied to all of the pods in this deployment
        app: url-shortener 
    spec:                         # Spec for the container which will run in the Pod
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers: 
      - name: url-shortener-api
        image: padraigmc/url-shortener-api:1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080  # Should match the port number that the Go application listens on
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          # To check if the Pod is ready to serve traffic or not
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service                       # Type of kubernetes resource
metadata:
  name: url-shortener-api-service   # Name of the resource
spec:
  selector:
    app: url-shortener              # Map any pod with label `app=url-shortener` to this service
  type: LoadBalancer
  ports:                            # Take incoming HTTP requests on port 8080 and forward them to the targetPort of 8080
  - name: http
    port: 8080
    targetPort: 8080